import { Request, Response } from 'express';
import {pool} from '../db';
import { deductStockForDeliveredOrder, hasDeliveredStockDeduction } from '../services/inventory.service';

/**
 * Create Delivery
 * POST /api/admin/deliveries
 * 
 * Creates delivery record for an order
 */
export const createDelivery = async (req: Request, res: Response) => {
    try {
        const {
            order_id,
            delivery_address,
            courier_name,
            courier_contact,
            pickup_address,
            estimated_delivery,
            notes
        } = req.body;

        // Validate order exists and is paid
        const orderResult = await pool.query(
            'SELECT id, status FROM orders WHERE id = $1',
            [order_id]
        );

        if (orderResult.rows.length === 0) {
            return res.status(404).json({ message: 'Order not found' });
        }

        if (orderResult.rows[0].status !== 'paid') {
            return res.status(400).json({ message: 'Order must be paid before creating delivery' });
        }

        // Check if delivery already exists for this order
        const existingDelivery = await pool.query(
            'SELECT id FROM deliveries WHERE order_id = $1',
            [order_id]
        );

        if (existingDelivery.rows.length > 0) {
            return res.status(400).json({ message: 'Delivery already exists for this order' });
        }

        // Create delivery (tracking number auto-generated by trigger)
        const result = await pool.query(
            `INSERT INTO deliveries 
             (order_id, delivery_address, courier_name, courier_contact, pickup_address, estimated_delivery, notes)
             VALUES ($1, $2, $3, $4, $5, $6, $7)
             RETURNING *`,
            [order_id, delivery_address, courier_name, courier_contact, pickup_address, estimated_delivery, notes]
        );

        res.status(201).json(result.rows[0]);
    } catch (error) {
        console.error('Error creating delivery:', error);
        res.status(500).json({ message: 'Server error' });
    }
};

/**
 * Get All Deliveries
 * GET /api/admin/deliveries?status=in_transit
 * 
 * Returns deliveries list with optional status filter
 */
export const getDeliveries = async (req: Request, res: Response) => {
    try {
        const { status } = req.query;

        let query = `
            SELECT 
                d.*,
                o.id as order_number,
                o.total_amount,
                u.full_name as customer_name,
                u.phone as customer_phone
            FROM deliveries d
            JOIN orders o ON d.order_id = o.id
            JOIN users u ON o.user_id = u.id
        `;

        const params: any[] = [];

        if (status && status !== 'all') {
            query += ' WHERE d.delivery_status = $1';
            params.push(status);
        }

        query += ' ORDER BY d.created_at DESC';

        const result = await pool.query(query, params);
        res.json(result.rows);
    } catch (error) {
        console.error('Error fetching deliveries:', error);
        res.status(500).json({ message: 'Server error' });
    }
};

/**
 * Get Delivery by ID
 * GET /api/admin/deliveries/:id
 */
export const getDeliveryById = async (req: Request, res: Response) => {
    try {
        const { id } = req.params;

        const result = await pool.query(
            `SELECT 
                d.*,
                o.id as order_number,
                o.total_amount,
                u.full_name as customer_name,
                u.email as customer_email,
                u.phone as customer_phone
             FROM deliveries d
             JOIN orders o ON d.order_id = o.id
             JOIN users u ON o.user_id = u.id
             WHERE d.id = $1`,
            [id]
        );

        if (result.rows.length === 0) {
            return res.status(404).json({ message: 'Delivery not found' });
        }

        res.json(result.rows[0]);
    } catch (error) {
        console.error('Error fetching delivery:', error);
        res.status(500).json({ message: 'Server error' });
    }
};

/**
 * Update Delivery Status
 * PATCH /api/admin/deliveries/:id/status
 * 
 * Updates delivery status and logs change
 */
export const updateDeliveryStatus = async (req: Request, res: Response) => {
    const client = await pool.connect();
    try {
        const { id } = req.params;
        const { delivery_status, notes } = req.body;
        const userId = (req as any).user?.id;
        await client.query('BEGIN');

        // Validate status
        const validStatuses = [
            'pickup_pending',
            'in_transit',
            'out_for_delivery',
            'delivered',
            'rto',
            'lost'
        ];

        if (!validStatuses.includes(delivery_status)) {
            await client.query('ROLLBACK');
            return res.status(400).json({
                message: 'Invalid delivery status',
                validStatuses
            });
        }

        // Get current delivery
        const deliveryResult = await client.query(
            'SELECT id, delivery_status, order_id FROM deliveries WHERE id = $1',
            [id]
        );

        if (deliveryResult.rows.length === 0) {
            await client.query('ROLLBACK');
            return res.status(404).json({ message: 'Delivery not found' });
        }

        const currentDelivery = deliveryResult.rows[0];
        const stockAlreadyDeducted = delivery_status === 'delivered'
            ? await hasDeliveredStockDeduction(client, currentDelivery.order_id)
            : false;

        // Update delivery status
        const updateResult = await client.query(
            `UPDATE deliveries 
             SET delivery_status = $1, 
                 actual_delivery = CASE WHEN $1 = 'delivered' THEN NOW() ELSE actual_delivery END,
                 updated_at = NOW()
             WHERE id = $2 
             RETURNING *`,
            [delivery_status, id]
        );

        // Log status change
        if (currentDelivery.delivery_status !== delivery_status) {
            await client.query(
                `INSERT INTO delivery_status_history 
                 (delivery_id, old_status, new_status, notes, changed_by)
                 VALUES ($1, $2, $3, $4, $5)`,
                [id, currentDelivery.delivery_status, delivery_status, notes || null, userId]
            );
        }

        // Update order status based on delivery status
        if (delivery_status === 'delivered') {
            await client.query(
                'UPDATE orders SET status = $1 WHERE id = $2',
                ['delivered', currentDelivery.order_id]
            );
            if (currentDelivery.delivery_status !== 'delivered' && !stockAlreadyDeducted) {
                await client.query(
                    `INSERT INTO order_status_history (order_id, old_status, new_status, notes, changed_by)
                     SELECT id, status, 'delivered', 'Updated via delivery workflow', $2
                     FROM orders
                     WHERE id = $1 AND status <> 'delivered'`,
                    [currentDelivery.order_id, userId || null]
                );
                await deductStockForDeliveredOrder(client, currentDelivery.order_id);
            }
        } else if (delivery_status === 'out_for_delivery') {
            await client.query(
                'UPDATE orders SET status = $1 WHERE id = $2',
                ['shipped', currentDelivery.order_id]
            );
        }

        await client.query('COMMIT');

        res.json({
            success: true,
            delivery: updateResult.rows[0],
            message: `Delivery status updated to ${delivery_status}`
        });
    } catch (error) {
        await client.query('ROLLBACK');
        console.error('Error updating delivery status:', error);
        res.status(500).json({ message: 'Server error' });
    } finally {
        client.release();
    }
};

/**
 * Get Delivery Status History
 * GET /api/admin/deliveries/:id/history
 */
export const getDeliveryStatusHistory = async (req: Request, res: Response) => {
    try {
        const { id } = req.params;

        const result = await pool.query(
            `SELECT 
                dsh.*,
                u.full_name as changed_by_name
             FROM delivery_status_history dsh
             LEFT JOIN users u ON dsh.changed_by = u.id
             WHERE dsh.delivery_id = $1
             ORDER BY dsh.changed_at DESC`,
            [id]
        );

        res.json(result.rows);
    } catch (error) {
        console.error('Error fetching delivery history:', error);
        res.status(500).json({ message: 'Server error' });
    }
};
